[package]
name = "markdown"
version = "0.1.0"
authors = ["Nick Floyd <nicholas.floyd.info@gmail.com>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
pulldown-cmark = "0.5.3"
wasm-bindgen = "0.2.50"