[package]
name = "rust"
version = "0.1.0"
authors = ["Nick Floyd <nicholas.floyd.info@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime-rust = "0.2"
failure = "0.1"